spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/addresses
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: none

server:
  port: 8081